name: Mem Kernel Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
          sudo apt update
          sudo apt install -y make bc bison flex libssl-dev \
            libncurses5-dev libelf-dev build-essential git \
            clang-17 lld-17
          
    - name: Checkout kernel source
      uses: actions/checkout@v4

    - name: Set up MemKernel as a module (M-OUT) with specified name
      run: |
        curl -LSs "https://raw.githubusercontent.com/subaktikesuma/MemKernel/main/kernel/setup.sh" | bash -s M TRXKernel

    - name: Android kernel build
      uses: lemniskett/android-kernel-actions@master
      id: build
      env:
        NAME: peridot
      with:
        arch: arm64
        compiler: clang/17
        defconfig: peridot_defconfig
        image: Image.gz-dtb

    - name: Upload Kernel and Module
      uses: actions/upload-artifact@v4
      with:
        name: module
        path: |
          ${{ steps.build.outputs.outfile }}
          ./out/drivers/memkernel/memkernel.ko
          
